{{- if .Values.collector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apolicy.collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "apolicy.collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector    
spec:
  replicas: {{ .Values.collector.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: collector
  template:
    metadata:
      labels:
        app.kubernetes.io/component: collector
    spec:
      serviceAccountName: {{ .Values.collector.serviceAccountName }}
      containers:
        - name: collector
          securityContext:
            {{- toYaml .Values.collector.securityContext | nindent 12 }}
          image: {{ .Values.collector.image }}
          resources:
            {{- toYaml .Values.collector.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          env:
            - name: K8S_HOST
              value:
            - name: K8S_REMOTE
              value: "false"
            - name: INCLUDED_NAMESPACES
              value:
            - name: EXCLUDED_NAMESPACES
              value: "{{ .Release.Namespace }}"
            - name: INCLUDED_WORKLOADS
              value:
            - name: EXCLUDED_WORKLOADS
              value:
{{- end }}