{{- if .Values.collector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.collector.serviceAccountName }}
{{- end }}
---
{{- if .Values.manager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.manager.serviceAccountName }}
{{- end }}
---
{{- if .Values.analyzer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.analyzer.serviceAccountName }}
{{- end }}