{{- if .Values.collector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.collector.serviceAccountName }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
---
{{- if .Values.manager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.manager.serviceAccountName }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
---
{{- if .Values.analyzer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.analyzer.serviceAccountName }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}